declare module "lucide-react" {
  import { FC, SVGProps } from "react";
  export type Icon = FC<SVGProps<SVGSVGElement> & { size?: number | string }>;

  // Layout & Navigation
  export const LayoutDashboard: Icon;
  export const Menu: Icon;
  export const X: Icon;
  export const ChevronLeft: Icon;
  export const ChevronRight: Icon;
  export const ChevronDown: Icon;
  export const ChevronUp: Icon;
  export const MoreHorizontal: Icon;
  export const ArrowLeft: Icon;
  export const ArrowRight: Icon;
  export const ArrowUpDown: Icon;

  // Core
  export const Home: Icon;
  export const Settings: Icon;
  export const Bell: Icon;
  export const Search: Icon;
  export const LogOut: Icon;
  export const Loader2: Icon;
  export const Check: Icon;
  export const CheckCheck: Icon;
  export const Save: Icon;
  export const Edit: Icon;
  export const Pencil: Icon;
  export const Pen: Icon;
  export const Trash2: Icon;
  export const Eye: Icon;
  export const EyeOff: Icon;
  export const Plus: Icon;
  export const Filter: Icon;
  export const Star: Icon;
  export const Link: Icon;
  export const Link2: Icon;
  export const Upload: Icon;
  export const Download: Icon;
  export const Play: Icon;
  export const ExternalLink: Icon;

  // People & Identity
  export const Users: Icon;
  export const User: Icon;
  export const UserPlus: Icon;
  export const UsersRound: Icon;
  export const UsersIcon: Icon;
  export const Crown: Icon;
  export const Baby: Icon;
  export const Heart: Icon;
  export const Skull: Icon;
  export const Hand: Icon;
  export const Shield: Icon;
  export const Lock: Icon;
  export const Droplets: Icon;
  export const Droplet: Icon;

  // Genealogy & Trees
  export const TreePine: Icon;

  // Media & Files
  export const FileText: Icon;
  export const File: Icon;
  export const Files: Icon;
  export const FileUp: Icon;
  export const FileDown: Icon;
  export const Image: Icon;
  export const Film: Icon;
  export const Music: Icon;
  export const Camera: Icon;
  export const Mic: Icon;

  // Communication
  export const Mail: Icon;
  export const AtSign: Icon;

  // Time & Location
  export const Clock: Icon;
  export const Calendar: Icon;
  export const MapPin: Icon;
  export const Map: Icon;
  export const Navigation: Icon;
  export const Globe: Icon;

  // Education & Work
  export const GraduationCap: Icon;
  export const Briefcase: Icon;

  // Book & Content
  export const BookOpen: Icon;
  export const BookMarked: Icon;
  export const BookCopy: Icon;

  // Data & Viz
  export const Activity: Icon;
  export const TrendingUp: Icon;
  export const RefreshCw: Icon;
  export const Zap: Icon;
  export const Sparkles: Icon;

  // Status & Alerts
  export const AlertTriangle: Icon;
  export const AlertCircle: Icon;
  export const CheckCircle2: Icon;
  export const HelpCircle: Icon;
  export const Inbox: Icon;
  export const Circle: Icon;

  // UI & Layout
  export const ZoomIn: Icon;
  export const ZoomOut: Icon;
  export const Maximize2: Icon;
  export const Route: Icon;
  export const CreditCard: Icon;
  export const HardDrive: Icon;
  export const GripVertical: Icon;

  // Additional icons
  export const Printer: Icon;
  export const SlidersHorizontal: Icon;
  export const Phone: Icon;
  export const Network: Icon;
  export const GitBranch: Icon;
  export const Flag: Icon;
  export const Award: Icon;
  export const Tag: Icon;
  export const Hash: Icon;
  export const Percent: Icon;
  export const Scissors: Icon;
  export const Copy: Icon;
  export const Clipboard: Icon;
  export const ClipboardList: Icon;
  export const History: Icon;
  export const RotateCcw: Icon;
  export const AlertOctagon: Icon;
  export const MinusCircle: Icon;
  export const CheckCircle: Icon;
  export const Book: Icon;
  export const Layers: Icon;
  export const Columns: Icon;
  export const Grid: Icon;
  export const BarChart: Icon;
  export const PieChart: Icon;
  export const Terminal: Icon;
  export const Code: Icon;
  export const Database: Icon;
  export const Server: Icon;
  export const Cpu: Icon;
  export const Monitor: Icon;
  export const Smartphone: Icon;
  export const Tablet: Icon;
  export const Wifi: Icon;
  export const Bluetooth: Icon;
  export const Battery: Icon;
  export const Power: Icon;
  export const Volume: Icon;
  export const Volume2: Icon;
  export const MicOff: Icon;
  export const Video: Icon;
  export const VideoOff: Icon;
  export const PhoneOff: Icon;
  export const PhoneCall: Icon;
  export const MessageCircle: Icon;
  export const MessageSquare: Icon;
  export const MessagesSquare: Icon;
  export const Send: Icon;
  export const InboxIcon: Icon;
  export const Archive: Icon;
  export const ArchiveRestore: Icon;
  export const Bookmark: Icon;
  export const BookmarkMinus: Icon;
  export const BookmarkPlus: Icon;
  export const TagIcon: Icon;
  export const Tags: Icon;
  export const Folder: Icon;
  export const FolderOpen: Icon;
  export const FolderTree: Icon;
  export const FileCode: Icon;
  export const FileJson: Icon;
  export const FileKey: Icon;
  export const FileLock: Icon;
  export const FileMinus: Icon;
  export const FilePlus: Icon;
  export const FileSearch: Icon;
  export const FileSignature: Icon;
  export const FileTextIcon: Icon;
  export const FileWarning: Icon;
  export const FileX: Icon;
  export const FileOutput: Icon;
  export const FileInput: Icon;
  export const FileBadge: Icon;
  export const FileBarChart: Icon;
  export const FileCheck: Icon;
  export const FileClock: Icon;
  export const FileCog: Icon;
  export const FileDiff: Icon;
  export const FileDigit: Icon;
  export const FileImage: Icon;
  export const FileMusic: Icon;
  export const FileVideo: Icon;
  export const FileArchive: Icon;
  export const FileSymlink: Icon;
  export const FileBox: Icon;
  export const FileSpreadsheet: Icon;
  export const FileStack: Icon;
  export const FilePen: Icon;
  export const FilePenLine: Icon;
  export const FileHeart: Icon;
  export const FileQuestion: Icon;
  export const FileKey2: Icon;
  export const FileLock2: Icon;
  export const FileDownIcon: Icon;
  export const FileUpIcon: Icon;
  export const FolderMinus: Icon;
  export const FolderPlus: Icon;
  export const FolderSearch: Icon;
  export const FolderClosed: Icon;
  export const FolderX: Icon;
  export const FolderCog: Icon;
  export const FolderCheck: Icon;
  export const FolderArchive: Icon;
  export const FolderHeart: Icon;
  export const FolderKey: Icon;
  export const FolderLock: Icon;
  export const FolderOutput: Icon;
  export const FolderInput: Icon;
  export const FolderSymlink: Icon;
  export const FolderTreeIcon: Icon;
  export const FolderUp: Icon;
  export const FolderDown: Icon;
  export const ShieldCheck: Icon;
  export const ShieldAlert: Icon;
  export const ShieldX: Icon;
  export const ShieldOff: Icon;
  export const ShieldQuestion: Icon;
  export const ShieldClose: Icon;
  export const ShieldBan: Icon;
  export const ShieldPlus: Icon;
  export const ShieldMinus: Icon;
  export const ShieldEllipsis: Icon;
  export const ShieldIcon: Icon;
  export const ShieldHalf: Icon;
  export const ShieldCheckIcon: Icon;
  export const ShieldAlertIcon: Icon;
  export const ShieldXIcon: Icon;
  export const ShieldOffIcon: Icon;
  export const ShieldQuestionIcon: Icon;
  export const ShieldCloseIcon: Icon;
  export const ShieldBanIcon: Icon;
  export const ShieldPlusIcon: Icon;
  export const ShieldMinusIcon: Icon;
  export const ShieldEllipsisIcon: Icon;
  export const ShieldHalfIcon: Icon;
}
